/*
 * GStreamer
 * Copyright (C) 2011-2013 Fabrizio Gennari <fabrizio.ge@tiscali.it>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Alternatively, the contents of this file may be used under the
 * GNU Lesser General Public License Version 2.1 (the "LGPL"), in
 * which case the following provisions apply instead of the ones
 * mentioned above:
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/**
 * SECTION:element-dmpdec
 *
 * Reads a DC2N DMP file and extract its Commodore TAP stream.
 *
 * <refsect2>
 * <title>Example launch line</title>
 * |[
 * gst-launch -v -m fakesrc ! dmpdec ! tapdec ! wavenc ! fakesink silent=TRUE
 * ]|
 * </refsect2>
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gst/gst.h>
#include <gst/base/gstadapter.h>
#include <string.h>

#include "gstdmpdec.h"

/* #defines don't like whitespacey bits */
#define GST_TYPE_DMPDEC \
  (gst_dmpdec_get_type())
#define GST_DMPDEC(obj) \
  (G_TYPE_CHECK_INSTANCE_CAST((obj),GST_TYPE_DMPDEC,GstDmpDec))
#define GST_DMPDEC_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_CAST((klass),GST_TYPE_DMPDEC,GstDmpDecClass))
#define GST_IS_DMPDEC(obj) \
  (G_TYPE_CHECK_INSTANCE_TYPE((obj),GST_TYPE_DMPDEC))
#define GST_IS_DMPDEC_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_TYPE((klass),GST_TYPE_DMPDEC))

typedef struct _GstDmpDec GstDmpDec;
typedef struct _GstDmpDecClass GstDmpDecClass;

struct _GstDmpDec
{
  GstElement element;

  GstPad *sinkpad, *srcpad;

  gboolean read_header;

  guchar bytes_per_sample;
  guint overflow;
  guint rate;

  GstAdapter *adapter;
  GstClockTime timestamp;
};

struct _GstDmpDecClass
{
  GstElementClass parent_class;
};

GST_DEBUG_CATEGORY_STATIC (gst_dmpdec_debug);
#define GST_CAT_DEFAULT gst_dmpdec_debug

/* the capabilities of the inputs and outputs.
 *
 * describe the real formats here.
 */
static GstStaticPadTemplate sink_factory = GST_STATIC_PAD_TEMPLATE ("sink",
    GST_PAD_SINK,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS ("audio/x-tap-dmp")
    );

static GstStaticPadTemplate src_factory = GST_STATIC_PAD_TEMPLATE ("src",
    GST_PAD_SRC,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS ("audio/x-tap, " "halfwaves = (boolean) FALSE ")
    );

G_DEFINE_TYPE (GstDmpDec, gst_dmpdec, GST_TYPE_ELEMENT);

/* GObject vmethod implementations */
static void
gst_dmpdec_finalize (GObject * object)
{
  GstDmpDec *dec = GST_DMPDEC (object);
  g_object_unref (dec->adapter);
}

/* GstElement vmethod implementations */
static GstStateChangeReturn
gst_dmpdec_change_state (GstElement * element, GstStateChange transition)
{
  GstDmpDec *dec = GST_DMPDEC (element);

  switch (transition) {
    case GST_STATE_CHANGE_READY_TO_PAUSED:
    case GST_STATE_CHANGE_PAUSED_TO_READY:
      dec->read_header = 0;
      dec->timestamp = 0;
      gst_adapter_clear (dec->adapter);
      break;
    default:
      break;
  }

  return GST_ELEMENT_CLASS (gst_dmpdec_parent_class)->change_state (element,
      transition);
}

/* initialize the dmpdec's class */
static void
gst_dmpdec_class_init (GstDmpDecClass * gclass)
{
  GstElementClass *element_class = GST_ELEMENT_CLASS (gclass);
  GObjectClass *object_class = G_OBJECT_CLASS (gclass);

  gst_element_class_set_details_simple (element_class,
      "Commodore DMP (format generated by DC2N devices) file reader",
      "Decoder/Audio",
      "Reads TAP data from DMP files",
      "Fabrizio Gennari <fabrizio.ge@tiscali.it>");

  gst_element_class_add_pad_template (element_class,
      gst_static_pad_template_get (&src_factory));
  gst_element_class_add_pad_template (element_class,
      gst_static_pad_template_get (&sink_factory));

  element_class->change_state = gst_dmpdec_change_state;
  object_class->finalize = gst_dmpdec_finalize;
}

/* chain function
 * this function does the actual processing
 */

#define DMPDEC_HEADER_SIZE 20

static GstFlowReturn
gst_dmpdec_chain (GstPad * pad, GstObject * parent, GstBuffer * buf)
{
  GstDmpDec *filter = GST_DMPDEC (parent);
  GstFlowReturn ret = GST_FLOW_OK;
  guint num_inpulses;
  gpointer header;

  gst_adapter_push (filter->adapter, buf);
  if (!filter->read_header
      && (header =
          gst_adapter_take (filter->adapter, DMPDEC_HEADER_SIZE)) != NULL) {
    const char expected_signature[] = "DC2N-TAP-RAW";
    guint8 *header_data = (guint8 *) header;
    gboolean header_valid;
    GstCaps *srccaps, *templatecaps;
    GstStructure *srcstructure;
    GValue rate = { 0 };
    guchar bits_per_sample;
    GstEvent *new_caps_event;
    GstEvent *new_segment_event;
    GstSegment new_segment;

    GST_DEBUG_OBJECT (filter, "Reading header");
    header_valid =
        !memcmp (header_data, expected_signature, strlen (expected_signature));
    header_data += strlen (expected_signature);
    header_valid = header_valid && ((*header_data++) == 0);     /* only version 0 supported */
    header_data += 2;           /* skip the 2 useless bytes in header */
    bits_per_sample = *header_data++;
    filter->bytes_per_sample = (bits_per_sample + 7) / 8;
    filter->overflow = (1 << bits_per_sample) - 1;
    g_value_init (&rate, G_TYPE_INT);
    filter->rate = GST_READ_UINT32_LE (header_data);
    g_value_set_int (&rate, filter->rate);
    g_free (header);

    if (!header_valid)
      return GST_FLOW_ERROR;

    templatecaps = gst_static_pad_template_get_caps (&src_factory);
    srccaps = gst_caps_copy (templatecaps);
    gst_caps_unref (templatecaps);
    srcstructure = gst_caps_get_structure (srccaps, 0);
    gst_structure_set_value (srcstructure, "rate", &rate);
    new_caps_event = gst_event_new_caps (srccaps);
    GST_DEBUG_OBJECT (filter, "Read header, set out caps %" GST_PTR_FORMAT,
        srccaps);

    gst_pad_push_event (filter->srcpad, new_caps_event);
    gst_caps_unref (srccaps);
    gst_segment_init (&new_segment, GST_FORMAT_TIME);
    new_segment_event = gst_event_new_segment (&new_segment);
    gst_pad_push_event (filter->srcpad, new_segment_event);
    filter->read_header = TRUE;
  }

  /* Don't go past this pojnt before finishing with the header */
  if (!filter->read_header)
    return GST_FLOW_OK;

  if ((num_inpulses =
          gst_adapter_available (filter->adapter) / filter->bytes_per_sample) >
      0) {
    guint num_inbytes = num_inpulses * filter->bytes_per_sample;
    guint num_outbytes;
    const guint8 *inbytes = gst_adapter_map (filter->adapter, num_inbytes);
    GstBuffer *newbuf =
        gst_buffer_new_allocate (NULL, num_inpulses * sizeof (guint), NULL);
    guint pos_inbyte, used_inbytes = 0, out_pulse = 0, pos_outpulse = 0;
    GstMapInfo map;
    guint *out_pulses;
    GstClockTime duration = 0;

    gst_buffer_map (newbuf, &map, GST_MAP_WRITE);
    out_pulses = (guint *) map.data;
    for (pos_inbyte = 0; pos_inbyte < num_inbytes;
        pos_inbyte += filter->bytes_per_sample) {
      guint inpulse;

      switch (filter->bytes_per_sample) {
        case 1:
          inpulse = inbytes[pos_inbyte];
          break;
        case 2:
          inpulse = GST_READ_UINT16_LE (inbytes + pos_inbyte);
          break;
        case 3:
          inpulse = GST_READ_UINT24_LE (inbytes + pos_inbyte);
          break;
        case 4:
        default:
          inpulse = GST_READ_UINT32_LE (inbytes + pos_inbyte);
          break;
      }
      out_pulse += inpulse;
      if (inpulse > filter->overflow)
        ret = GST_FLOW_ERROR;
      else if (inpulse < filter->overflow) {
        out_pulses[pos_outpulse++] = out_pulse;
        duration += out_pulse;
        out_pulse = 0;
        used_inbytes = pos_inbyte + filter->bytes_per_sample;
      }
    }
    gst_adapter_flush (filter->adapter, used_inbytes);
    gst_buffer_unmap (newbuf, &map);
    gst_adapter_unmap (filter->adapter);
    if ((num_outbytes = pos_outpulse * sizeof (guint)) > 0) {
      gst_buffer_resize (newbuf, 0, num_outbytes);
      GST_BUFFER_DTS (newbuf) = filter->timestamp;
      duration = gst_util_uint64_scale (duration, GST_SECOND, filter->rate);
      GST_BUFFER_DURATION (newbuf) = duration;
      filter->timestamp += duration;
      GST_LOG_OBJECT (filter, "pushing %" GST_PTR_FORMAT, newbuf);
      ret = gst_pad_push (filter->srcpad, newbuf);
    } else
      gst_buffer_unref (newbuf);
  }

  return ret;
}

static gboolean
gst_dmpdec_event (GstPad * pad, GstObject * parent, GstEvent * event)
{
  GST_LOG ("handling %s event", GST_EVENT_TYPE_NAME (event));

  switch (GST_EVENT_TYPE (event)) {
    case GST_EVENT_CAPS:
    case GST_EVENT_SEGMENT:
      GST_DEBUG ("eating event");
      gst_event_unref (event);
      return TRUE;
    default:
      GST_DEBUG ("forwarding event");
      return gst_pad_event_default (pad, parent, event);
  }
}

/* initialize the new element
 * instantiate pads and add them to element
 * set pad calback functions
 * initialize instance structure
 */

static void
gst_dmpdec_init (GstDmpDec * filter)
{
  filter->sinkpad = gst_pad_new_from_static_template (&sink_factory, "sink");
  gst_pad_set_chain_function (filter->sinkpad,
      GST_DEBUG_FUNCPTR (gst_dmpdec_chain));

  filter->srcpad = gst_pad_new_from_static_template (&src_factory, "src");
  gst_pad_set_event_function (filter->sinkpad, gst_dmpdec_event);
  gst_element_add_pad (GST_ELEMENT (filter), filter->sinkpad);
  gst_element_add_pad (GST_ELEMENT (filter), filter->srcpad);

  filter->adapter = gst_adapter_new ();
  filter->read_header = FALSE;
}

gboolean
gst_dmpdec_register (GstPlugin * plugin)
{
  GST_DEBUG_CATEGORY_INIT (gst_dmpdec_debug, "dmpdec",
      0, "Commodore 64 DMP encoder");

  return gst_element_register (plugin, "dmpdec", GST_RANK_MARGINAL,
      GST_TYPE_DMPDEC);
}
