/*
 * GStreamer
 * Copyright (C) 2011-2013 Fabrizio Gennari <fabrizio.ge@tiscali.it>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Alternatively, the contents of this file may be used under the
 * GNU Lesser General Public License Version 2.1 (the "LGPL"), in
 * which case the following provisions apply instead of the ones
 * mentioned above:
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 */

/**
 * SECTION:element-dmpdec
 *
 * Reads a DC2N DMP file and extract its Commodore TAP stream.
 *
 * <refsect2>
 * <title>Example launch line</title>
 * |[
 * gst-launch -v -m fakesrc ! dmpdec ! tapdec ! wavenc ! fakesink silent=TRUE
 * ]|
 * </refsect2>
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gst/gst.h>

#include "gstdmpdec.h"

/* #defines don't like whitespacey bits */
#define GST_TYPE_DMPDEC \
  (gst_dmpdec_get_type())
#define GST_DMPDEC(obj) \
  (G_TYPE_CHECK_INSTANCE_CAST((obj),GST_TYPE_DMPDEC,GstDmpDec))
#define GST_DMPDEC_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_CAST((klass),GST_TYPE_DMPDEC,GstDmpDecClass))
#define GST_IS_DMPDEC(obj) \
  (G_TYPE_CHECK_INSTANCE_TYPE((obj),GST_TYPE_DMPDEC))
#define GST_IS_DMPDEC_CLASS(klass) \
  (G_TYPE_CHECK_CLASS_TYPE((klass),GST_TYPE_DMPDEC))

typedef struct _GstDmpDec GstDmpDec;
typedef struct _GstDmpDecClass GstDmpDecClass;

struct _GstDmpDec
{
  GstBaseTapContainerDec element;

  guchar bytes_per_sample;
  guint overflow;
};

struct _GstDmpDecClass
{
  GstBaseTapContainerDecClass parent_class;

  guchar bytes_per_sample;
  guint overflow;
};

GST_DEBUG_CATEGORY_STATIC (gst_dmpdec_debug);
#define GST_CAT_DEFAULT gst_dmpdec_debug


G_DEFINE_TYPE (GstDmpDec, gst_dmpdec, GST_TYPE_BASETAPCONTAINERDEC);

static gsize gst_dmpdec_get_header_size (GstBaseTapContainerDec * filter);
static GstBaseTapContainerHeaderStatus
gst_dmpdec_read_header (GstBaseTapContainerDec * filter,
    const guint8 * header_data);
static gboolean gst_dmpdec_read_pulse (GstBaseTapContainerDec * filter,
    GstBaseTapContainerReadData read_data, guint * pulse);

/* initialize the dmpdec's class */
static void
gst_dmpdec_class_init (GstDmpDecClass * gclass)
{
  GstBaseTapContainerDecClass *parent_class = GST_BASETAPCONTAINERDEC_CLASS (gclass);
  GstElementClass *element_class = GST_ELEMENT_CLASS (gclass);

  gst_element_class_set_details_simple (element_class,
      "Commodore DMP (format generated by DC2N devices) file reader",
      "Decoder/Audio",
      "Reads TAP data from DMP files",
      "Fabrizio Gennari <fabrizio.ge@tiscali.it>");

  parent_class->get_header_size = gst_dmpdec_get_header_size;
  parent_class->read_header = gst_dmpdec_read_header;
  parent_class->read_pulse = gst_dmpdec_read_pulse;

  gst_basetapcontainerdec_sink_factory (parent_class, "audio/x-tap-dmp");
}

/* chain function
 * this function does the actual processing
 */

#define DMPDEC_HEADER_SIZE 20

static gsize
gst_dmpdec_get_header_size (GstBaseTapContainerDec * filter)
{
  return DMPDEC_HEADER_SIZE;
}

static GstBaseTapContainerHeaderStatus
gst_dmpdec_read_header (GstBaseTapContainerDec * filter,
    const guint8 * header_data)
{
  const char expected_signature[] = "DC2N-TAP-RAW";
  GstDmpDec *decoder = GST_DMPDEC (filter);
  gboolean header_valid;
  guchar bits_per_sample;
  guchar version;

  GST_DEBUG_OBJECT (filter, "Reading header");
  header_valid =
        !memcmp (header_data, expected_signature, strlen (expected_signature));
  header_data += strlen (expected_signature);
  version = *header_data++;
  header_valid = header_valid && (version == 0 || version == 1);
  filter->halfwaves = ((*header_data++) >> 4) & 1; /* ignore bits but the 4th one in this byte in header */
  header_data ++;           /* skip the useless byte in header */
  bits_per_sample = *header_data++;
  decoder->bytes_per_sample = (bits_per_sample + 7) / 8;
  decoder->overflow = (1 << bits_per_sample) - 1;
  filter->rate = GST_READ_UINT32_LE (header_data);

  if (!header_valid)
    return GST_BASE_TAP_CONVERT_NO_VALID_HEADER;

  return GST_BASE_TAP_CONVERT_VALID_HEADER;
}

static gboolean
gst_dmpdec_read_pulse (GstBaseTapContainerDec * filter,
    GstBaseTapContainerReadData read_data, guint * pulse)
{
  GstDmpDec *decoder = GST_DMPDEC (filter);
  *pulse = 0;

  while (1) {
    guint inpulse;
    const guint8 *inbytes = read_data (filter, decoder->bytes_per_sample);
    if (inbytes == NULL)
      return FALSE;

    switch (decoder->bytes_per_sample) {
      case 1:
        inpulse = inbytes[0];
        break;
      case 2:
        inpulse = GST_READ_UINT16_LE (inbytes);
        break;
      case 3:
        inpulse = GST_READ_UINT24_LE (inbytes);
        break;
      case 4:
      default:
        inpulse = GST_READ_UINT32_LE (inbytes);
        break;
    }
    *pulse += inpulse;
    if (inpulse > decoder->overflow)
      return FALSE;
    if (inpulse < decoder->overflow)
      return TRUE;
  }
}
static void
gst_dmpdec_init (GstDmpDec * filter)
{
}

gboolean
gst_dmpdec_register (GstPlugin * plugin)
{
  GST_DEBUG_CATEGORY_INIT (gst_dmpdec_debug, "dmpdec",
      0, "Commodore 64 DMP encoder");

  return gst_element_register (plugin, "dmpdec", GST_RANK_MARGINAL,
      GST_TYPE_DMPDEC);
}
